/* The nine worlds: names, section labels, guide lines and fonts. */
/* ================= WORLDS ================= */
const FONTS={
  anthro:'Luckiest+Guy&family=Fredoka:wght@400;500;600;700',
  kawaii:'Mochiy+Pop+One&family=M+PLUS+Rounded+1c:wght@400;700',
  kitsch:'Shrikhand&family=Karla:wght@400;600;700',
  graffiti:'Sedgwick+Ave+Display&family=Rubik+Wet+Paint&family=Rubik:wght@400;600',
  gothic:'UnifrakturMaguntia&family=Cormorant+Garamond:wght@500;600;700',
  doodle:'Caveat+Brush&family=Patrick+Hand',
  medieval:'Uncial+Antiqua&family=IM+Fell+English:ital@0;1',
  pixel:'Press+Start+2P&family=Pixelify+Sans:wght@400;600',
  y2k:'Audiowide&family=Chakra+Petch:wght@400;600',
};
const WORLDS={
  anthro:{title:'Deep Dive',style:'Anthropomorphic',tag:'An underwater quest with a critter crew',font:'Luckiest Guy',coll:['pearl','pearls'],proj:'pan',fx:'bubble',
    preview:'linear-gradient(180deg,#8FE3F7,#1E9BD7 55%,#0A1E45)',
    stops:['Surface','Reef','Crew','Wreck','Trench','Abyss'],
    eb:['Portfolio · Nairobi · 0 m','The reef · 20 m','The crew quarters · 80 m','The shipwreck · 200 m','The trench · 600 m','The abyss · 1,000 m'],
    cta:['Start the dive ↓','Skip to projects'],crewTitle:'Meet the crew',crewIntro:'Everything I do, played by the critters who help me do it. Hover one to hear from them.',
    projTitle:'Treasure in the wreck',projIntro:"Four things I've built or designed. Keep scrolling and the wreck slides past.",hint:'Scroll → explore',
    pathTitle:'How I build: the dive plan',contactTitle:'You made it to the bottom!',contactText:'Got a role, a project, or a website? Drop me a line.',send:'Toss a message in a bottle',
    num:i=>'0'+(i+1),foot:'Made underwater in Nairobi',
    lines:["Hi! I'm Karen. Grab a snorkel, we're going down.","This is me. Well, me in a helmet.","Meet my crew. Each one handles something I do.","My projects sank here. Keep scrolling to explore the wreck.","Here's how I build, one stop at a time. Mind the drop!","You made it to the bottom! Say hi?"]},
  kawaii:{title:'Sakura Café',style:'Anime',tag:'A shoujo-anime café in cherry blossom season',font:'Mochiy Pop One',coll:['mochi','mochi'],proj:'grid',fx:'petal',
    preview:'linear-gradient(180deg,#FFE3F1,#F3DCFF 55%,#CFEFFF)',
    stops:['Door','Counter','Staff','Bento','Recipe','Order'],
    eb:['Portfolio · Nairobi · Now open','At the counter',"Today's staff","Chef's bento",'The recipe','Place your order'],
    cta:['Come on in ♡','Peek at the bento'],crewTitle:'Meet the café staff',crewIntro:'Every service on the menu, served by a tiny critter who loves their job.',
    projTitle:"Chef's special bento",projIntro:'Four projects, packed with care into one lunchbox.',hint:'',
    pathTitle:'My recipe for building',contactTitle:'Ready to order?',contactText:"Craving a role, a project, or a website? Tell me your order and I'll cook something up.",send:'Send my order ♡',
    num:i=>'0'+(i+1),foot:'Baked with love in Nairobi',
    lines:["Welcome to Sakura Café! The blossoms are out today.","That's me behind the counter. Hi hi!","Meet the staff! They're very hardworking.","Chef's bento: four projects, freshly packed.","Every good recipe has steps. Here's how I build.","Your order goes straight to the kitchen!"]},
  kitsch:{title:'The Karen Show',style:'Kitsch',tag:'A retro TV game show, live on air',font:'Shrikhand',coll:['golden token','golden tokens'],proj:'grid',fx:'confetti',
    preview:'linear-gradient(180deg,#FF3EA5,#7B2FF7 60%,#1A0638)',
    stops:['Studio','Contestant','Co-hosts','Prize doors','Game plan','Call in'],
    eb:['Live from Nairobi · On air',"Tonight's contestant",'Your co-hosts','Behind the prize doors','The game plan','Phone lines are open'],
    cta:['Come on down!','Open the doors'],crewTitle:'Give it up for the co-hosts!',crewIntro:'Five dazzling specialists, one fabulous engineer. Hover to hear their catchphrases.',
    projTitle:"What's behind door number...",projIntro:'Four fabulous prizes, all built by our contestant.',hint:'',
    pathTitle:'How to win the grand prize',contactTitle:'Call in now!',contactText:'Operators are standing by. Well, Karen is. Got a role, a project, or a website? Call in!',send:'Place the call',
    num:i=>'DOOR '+(i+1),foot:'Broadcast live from Nairobi',
    lines:["Welcome to The Karen Show! Big applause!","Our contestant tonight: a software engineer from Nairobi!","Let's meet the fabulous co-hosts!","Four doors, four prizes. No duds, I promise.","Here's her winning strategy, step by step!","Lines are open! Don't be shy."]},
  graffiti:{title:'Wet Paint',style:'Graffiti',tag:'Tags, drips and stickers on a city wall',font:'Sedgwick Ave Display',coll:['spray can','spray cans'],proj:'pan',fx:'spray',
    preview:'radial-gradient(circle at 30% 30%,#FF2E97,transparent 50%),radial-gradient(circle at 70% 70%,#39FF14,transparent 50%),#1D1D22',
    stops:['The wall','The artist','The crew','Pieces','The process','Leave a tag'],
    eb:['Nairobi · Street art · Wet paint','Meet the artist','The crew','Pieces on the wall','From sketch to wall','Leave your tag'],
    cta:['Hit the wall','See the pieces'],crewTitle:'The crew',crewIntro:'Five crew members, each with their own tag. Hover to hear them.',
    projTitle:'Pieces on the wall',projIntro:"Four pieces I've put up. Scroll and the wall rolls past.",hint:'Scroll → more pieces',
    pathTitle:'How a piece gets made',contactTitle:'Leave your tag',contactText:'Got a role, a project, or a website? Drop a line on the wall.',send:'Tag it',
    num:i=>'PIECE 0'+(i+1),foot:'Painted in Nairobi',
    lines:["Yo! Welcome to the wall. Mind the wet paint.","That's me. Artist and engineer.","The crew. Everybody's got a tag.","My pieces. Scroll to see them all.","Every piece starts as a sketch. Here's how I build.","Leave your tag. I'll see it."]},
  gothic:{title:'The Midnight Library',style:'Gothic',tag:'A candlelit castle library after dark',font:'UnifrakturMaguntia',coll:['golden key','golden keys'],proj:'grid',fx:'ember',
    preview:'radial-gradient(circle at 75% 20%,#5A4580,#1A1226 45%,#07050A)',
    stops:['Gates','Portrait','Guild','Archive','Stairway','Scriptorium'],
    eb:['Portfolio · Nairobi · By candlelight','The portrait hall','The guild of five','The restricted archive','The winding stair','The scriptorium'],
    cta:['Enter the library','To the archive'],crewTitle:'The Guild of Five',crewIntro:'Each keeper guards one of my crafts. Hover to hear them whisper.',
    projTitle:'The restricted archive',projIntro:'Four volumes, each a thing I built. Handle with care.',hint:'',
    pathTitle:'The winding stair of craft',contactTitle:'Seal a letter',contactText:'A role, a project, or a website? Write to me by candlelight. I answer every letter.',send:'Seal and send',
    num:i=>'Vol. '+['I','II','III','IV'][i],foot:'Written by candlelight in Nairobi',
    lines:["Welcome, traveller. Mind the cobwebs.","My portrait. Painted by moonlight.","The Guild of Five keeps my crafts safe.","The archive holds four volumes. Read freely.","Six steps of craft, each one carefully carved.","The scriptorium. Leave a letter if you wish."]},
  doodle:{title:"Karen's Notebook",style:'Doodle',tag:'A school notebook full of scribbles',font:'Caveat Brush',coll:['gold sticker','gold stickers'],proj:'grid',fx:'ink',
    preview:'linear-gradient(#DCE6F7 1px,transparent 1px) 0 0/14px 14px,#FDFBF4',
    stops:['Cover','Page 1','Squad','Notes','Process','Back page'],
    eb:['portfolio · nairobi · property of karen','page 1: about me','the doodle squad','sticky notes','my process','the back page'],
    cta:['open the notebook','skip to my notes'],crewTitle:'The doodle squad',crewIntro:'I doodle when I think. These five turned into my job description.',
    projTitle:'Stuck to the page',projIntro:'Four projects I keep coming back to.',hint:'',
    pathTitle:'how i build (step by step!)',contactTitle:'Pass me a note!',contactText:'got a role, a project, or a website? scribble it here.',send:'Fold and pass it',
    num:i=>'#'+(i+1),foot:'scribbled in nairobi',
    lines:["hi!! welcome to my notebook :)","page 1 is all about me","meet the doodle squad!","my favorite pages. don't peel the notes off!","my process, in six messy steps.","pass me a note! i promise to write back."]},
  medieval:{title:'The Illuminated Codex',style:'Medieval',tag:'A hand-painted manuscript, margins and all',font:'Uncial Antiqua',coll:['golden quill','golden quills'],proj:'grid',fx:'gold',
    preview:'radial-gradient(ellipse at 50% 30%,#FBF1D6,#E6D2A2 70%)',
    stops:['Frontispiece','Portrait','The Order','Folios','Tapestry','Missive'],
    eb:['Portfolio · Nairobi · Anno MMXXVI','Portrait of the scribe','The noble order','Folios of works','The tapestry of craft','Send a missive'],
    cta:['Open the codex','Turn to the folios'],crewTitle:'The Noble Order',crewIntro:'Five sworn companions, each bearing a coat of arms. Hover to hear their oath.',
    projTitle:'Folios of works',projIntro:'Four works, each set down on its own page.',hint:'',
    pathTitle:'The tapestry of craft',contactTitle:'Send a missive',contactText:'A role, a project, or a website? Dispatch a missive. Replies arrive swiftly, by pigeon.',send:'Dispatch by pigeon',
    num:i=>'Folio '+['I','II','III','IV'][i],foot:'Illuminated by hand in Nairobi',
    lines:["Welcome, good traveller. Pray, turn the page.","Behold: a portrait of the scribe.","The Noble Order stands ready to serve.","Four folios, painted with care.","Each step of the craft, woven by hand.","Send a missive. The pigeon awaits."]},
  pixel:{title:'Karen Quest',style:'Pixel art',tag:'An 8-bit adventure, one player',font:'Press Start 2P',coll:['coin','coins'],proj:'pan',fx:'pixel',
    preview:'linear-gradient(180deg,#1B1B3A,#241A4A 70%,#3EE06D 70% 78%,#8B5A2B 78%)',
    stops:['Title','Player 1','Party','Levels','World map','Continue'],
    eb:['Nairobi · 1 player · Press start','Player 1 select','Your party','Level select','World map','Continue?'],
    cta:['▶ Press start','Level select'],crewTitle:'Choose your party',crewIntro:'Five party members, each with one special skill. Hover to hear their battle cry.',
    projTitle:'Level select',projIntro:'Four levels cleared. Scroll to browse.',hint:'Scroll → next level',
    pathTitle:'World map: how I build',contactTitle:'Continue?',contactText:'Got a role, a project, or a website? Insert a message to join the party.',send:'Insert coin',
    num:i=>'1-'+(i+1),foot:'Made in Nairobi · 1 player',
    lines:["A new quest begins! Press start.","Player 1: Karen. Class: software engineer.","Your party is ready for battle.","Four levels cleared. Pick one!","Six levels. Every build clears all of them.","Game over? Nope. Continue!"]},
  y2k:{title:'KarenOS 2000',style:'Y2K',tag:'A glossy desktop straight from 2000',font:'Audiowide',coll:['floppy disk','floppy disks'],proj:'grid',fx:'sparkle',
    preview:'linear-gradient(180deg,#D8F6FF,#D9D0FF 60%,#FAD6F4)',
    stops:['Boot','My profile','Buddy list','Programs','Process','Guestbook'],
    eb:['KarenOS 2000 · Nairobi · Loaded 100%','my_profile.htm','Buddy list · 5 online','C:\\Programs','build_process.exe','guestbook.exe'],
    cta:['Log on','Open programs'],crewTitle:'Buddy list',crewIntro:'5 buddies online. Each one runs a program I build. Hover to see their away message.',
    projTitle:'Programs',projIntro:'Four programs installed. On a computer, drag the windows around.',hint:'',
    pathTitle:'build_process.exe',contactTitle:'Sign my guestbook!',contactText:'Got a role, a project, or a website? Sign the guestbook. No spam, pinky promise.',send:'Sign guestbook',
    num:i=>'0'+(i+1),foot:'KarenOS 2000 · Nairobi',
    lines:["KarenOS 2000 has finished loading. Welcome!","This is my profile. Very 2000.","My buddies are all online right now.","Programs installed. Drag the windows around!","build_process.exe: six steps, zero crashes.","Sign the guestbook before you log off!"]},
};
const ORDER=['anthro','kawaii','kitsch','graffiti','gothic','doodle','medieval','pixel','y2k'];
